# 1교시 : 과제

## 1. r^2 scores는 0에 가까울수록 좋다
X
-> 1에 가까울수록 좋다

## 2. lr.intercept_ 의 의미는?

-> y절편

## 3. 식에서 lr.coef_ 가 지칭하는 것은? 

y = b + b1 * x1 + b2 * x2 + b3 * x3  
-> b1, b2, b3

## 4. 선형회귀 분석의 기본 가정은?

두 변수의 관계는 ( _____  ) 이다.  -> 선형  
-> 선형성

오차항의 확률분포는 ( ______ )를 이룬다. -> 정규분포  
-> 오차의 정규성

오차항의 평균은 ( _____ ) 이다. -> 0

오차항들끼리는 ( ____ ) 이다. -> 독립  
-> 영향을 미치지 않는다

## 5. cars 속도가 70, 90, 100 일 때의 제동거리를 신뢰도 99%로 예측하는 코드를 작성하세요

## 5-2. 파이썬으로 불러오기

In [27]:
import pandas as pd
import numpy as np

In [28]:
pd.read_csv('C:\Rdata\cars.csv')

Unnamed: 0  speed  dist
0            1      4     2
1            2      4    10
2            3      7     4
3            4      7    22
4            5      8    16
5            6      9    10
6            7     10    18
7            8     10    26
8            9     10    34
9           10     11    17
10          11     11    28
11          12     12    14
12          13     12    20
13          14     12    24
14          15     12    28
15          16     13    26
16          17     13    34
17          18     13    34
18          19     13    46
19          20     14    26
20          21     14    36
21          22     14    60
22          23     14    80
23          24     15    20
24          25     15    26
25          26     15    54
26          27     16    32
27          28     16    40
28          29     17    32
29          30     17    40
30          31     17    50
31          32     18    42
32          33     18    56
33          34     18    76
34          35     18    84
35          36     19    36
36          37     19    46
37          38     19    68
38          39     20    32
39          40     20    48
40          41     20    52
41          42     20    56
42          43     20    64
43          44     22    66
44          45     23    54
45          46     24    70
46          47     24    92
47          48     24    93
48          49     24   120
49          50     25    85

In [31]:
cars = pd.read_csv('C:\Rdata\cars.csv')[['speed','dist']]
cars[:5]

speed  dist
0      4     2
1      4    10
2      7     4
3      7    22
4      8    16

In [34]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [37]:
X = cars[['speed']]
y = cars[['dist']]

In [39]:
lr.fit(X,y)

LinearRegression()

In [41]:
pred = lr.predict(np.array([70,90,100]).reshape(-1,1))

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [42]:
pred

array([[257.68951825],
       [336.33769343],
       [375.66178102]])

In [ ]:
lr = LinearRegression()
lr.fit(cars['speed'].values.reshape(-1, 1),cars['dist'])
lr.predict(np.array([70,90,100]).reshape(-1,1))

## 6. 총제곱합 SST = ?

SSR + SSE  
(회귀제곱합) + (오차제곱합)

## 7. 결정계수 = ? 

$R^2$ = $r^2$ = 모형의 설명력 = $SSR/SST$ = 1에 가까울 수록 좋다 = 1 - SSE $/$ SST

## 8. 다음 괄호를 채우시오

선형분석은 기본적으로 ( ___ ) 관계를 규명하는 것이다.  

-> 인과

원인으로 간주되는 변수 X를 ( ___ ), 종속변수 y를 ( __ ) 라고 부른다  

-> 설명변수, 반응변수

## 9. 선형회귀의 평가지표 metrics 는?

MAE (Mean Absolute Error)  
MSE (Mean Squared Error)  
RMSE (Root Mean Squared Error)  
R^2

## 10. OLS 는 ?

최소제곱법(Ordinary Least Squares)

## 11. 상관분석은 인과관계를 가정한다. (O, X)

-> X

## 12. 분류와 회귀의 큰 차이는 분류의 예측값은 ( ____ ) 이고, 회귀의 예측값은 ( ____ ) 라는 것이다.

범주형, 숫자형

## 13. IQR을 이용해 이상치 데이터를 검출하는 방식

1/4 ( _____ )  -> (1/4*100) - 1.5*IQR  
3/4 ( _____ )  -> (3/4*100) + 1.5*IQR

## 14. 여러 알고리즘을 사용하여 예측 결과를 만들고 그 예측 결과들을 모아 다시 학습하여 최종 예측 결과물을 도출하는 앙상블 기법은?

Stacking ( 스택킹 )

## 15. SMOTE 기법 ? 

최근접 이웃[k-NN 알고리즘] 알고리즘을 활용하여 '오버샘플링' 하는 방법 

## 16. 데이터를 log값으로 변환하는 이유는?

큰 값을 상대적으로 작게 만들어 데이터 분포도의 왜곡을 완화시키기 위해

## 17. 빈 칸을 채우세요

MSE에 루트는 씌운 것 ( ____ ) -> RMSE <br/> 실제값과 예측값의 차이를 절대값을 변환해 평균한 것 ( ____ ) -> MAE <br/> 실제값의 분산 대비 예측값의 분산 비율을 지표로 하며, 1에 가까울수록 예측 정확도가 높다 ( _____ ) -> R^2 <br/> 실제값과 예측값의 차이를 제곱 해 평균한 것 ( ____ ) -> MSE

# 2교시 : 327p ~ , 다중선형회귀분선 ppt 자료

# 3교시 : 327p ~ 

In [83]:
from sklearn.preprocessing import PolynomialFeatures

In [88]:
X = np.arange(4)[:, np.newaxis] # 축을 추가하겠다
X

array([[0],
       [1],
       [2],
       [3]])

In [89]:
np.arange(4).reshape(-1,1)

array([[0],
       [1],
       [2],
       [3]])

In [91]:
np.arange(4)[np.newaxis,:].shape

(1, 4)

In [92]:
X = np.arange(4)[:, np.newaxis] # 객체생성

poly = PolynomialFeatures(degree=2) # 2차식으로 만들어주겠다
poly_ftr = poly.fit_transform(X)
poly_ftr

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.],
       [1., 3., 9.]])

In [94]:
# 정답에 해당하는 함수 만들기
def polynomial_func(X):
      y = 1 + 2*X + 3*X**2 + 4*X**3
      return y

In [96]:
polynomial_func(X)

array([[  1],
       [ 10],
       [ 49],
       [142]])

In [98]:
y = polynomial_func(X)
y

array([[  1],
       [ 10],
       [ 49],
       [142]])

In [99]:
model = LinearRegression()
model.fit(poly_ftr,y)

LinearRegression()

In [100]:
model.coef_

array([[  0. , -16.8,  21. ]])

In [104]:
# degree 를 3으로 설정했을 때
X = np.arange(4)[:, np.newaxis] # 객체생성

poly = PolynomialFeatures(degree=3) # 3차식으로 만들어주겠다
poly_ftr = poly.fit_transform(X)

y = polynomial_func(X)

model = LinearRegression()
model.fit(poly_ftr,y)

model.coef_

array([[0., 2., 3., 4.]])

In [107]:
# 책처럼 변환하면

In [109]:
X = np.arange(4).reshape(2,2)
X

array([[0, 1],
       [2, 3]])

In [110]:
poly = PolynomialFeatures(degree=3) 
poly_ftr = poly.fit_transform(X)
poly_ftr

array([[ 1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27.]])

In [113]:
def polynomial_func(X):
      y = 1 + 2*X[:,0] + 3*X[:,0]**2 + 4*X[:,1]**3
      return y

In [114]:
y = polynomial_func(X)
y

array([  5, 125])

In [115]:
model = LinearRegression()
model.fit(poly_ftr,y)

LinearRegression()

In [116]:
model.coef_

array([0.        , 0.18018018, 0.18018018, 0.36036036, 0.54054054,
       0.72072072, 0.72072072, 1.08108108, 1.62162162, 2.34234234])

# 5교시 : 332p ~ 다항회귀 과소적합, 과적합

## 337p : 릿지,리쏘, 엘라스틱넷 - 내용만 알면 됨

# 6교시 : 릿지회귀 - 339p ~ 

In [121]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import cross_val_score

In [124]:
import pandas as pd
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data"
names = ["CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B", "LSTAT", "MEDV"]
data = pd.read_csv(url, delim_whitespace=True, names=names)
data 

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [126]:
X_data = data.iloc[:,:-1]
y_target = data.iloc[:,-1]
y_target[:3]
X_data[:3]

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03

In [131]:
ridge = Ridge()
MSE = cross_val_score(ridge, X_data, y_target, scoring = 'neg_mean_squared_error', cv=5, n_jobs=-1)

In [132]:
-MSE

array([11.7110334 , 23.58316804, 29.69339407, 80.22988232, 31.11617767])

In [133]:
np.mean(-MSE)

35.26673109749667

In [136]:
RMSE = np.sqrt(np.mean(-MSE))
RMSE

5.938579888954654

### 3:1 로 분리하여 MSE값을 구하면?

In [139]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_data, y_target, test_size=0.25)
ridge = Ridge()
ridge.fit(X_train, y_train)
pred = ridge.predict(X_test)

from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, pred)

23.366028536099964

### alpha = [0.1, 0.5, 1, 2, 5, 10]에 대한 mean_squared_error 6개를 구해 봅시다.

In [146]:
alphas = [0.1, 0.5, 1, 2, 5, 10]
for alpha in alphas :
      ridge = Ridge(alpha = alpha)
      
      ridge.fit(X_train, y_train)

      pred = ridge.predict(X_test)

      print(mean_squared_error(y_test, pred))

29.813805361779558
30.095600808391158
30.32063582434389
30.547330726740793
30.656982688315313
30.475597888992937


### Lasso 회귀

In [149]:
from sklearn.linear_model import Lasso

In [148]:
alphas = [0.1, 0.5, 1, 2, 5, 10]
for alpha in alphas :
      lasso = Lasso(alpha = alpha)
      
      lasso.fit(X_train, y_train)

      pred = lasso.predict(X_test)

      print(mean_squared_error(y_test, pred))

31.155620239421204
30.081556297588353
30.88361883946248
36.341538152741954
42.97482890913368
48.456014378550364


### 엘라스틱넷 회귀 : 라쏘와 릿지를 둘 다 고려함

In [151]:
from sklearn.linear_model import ElasticNet
alphas = [0.1, 0.5, 1, 2, 5, 10]
for alpha in alphas :
      elastic = ElasticNet(alpha = alpha)
      
      elastic.fit(X_train, y_train)

      pred = elastic.predict(X_test)

      print(mean_squared_error(y_test, pred))

30.16071407953616
29.66544138114391
30.735594884222355
33.307084241076225
39.93463938060249
45.8213615365072


### 350p - 로지스틱 회귀

로지스틱 함수 > 시그모이드 함수 

![Image Description](sigmoid.png) -> 기울기 소실 문제 해결책으로 나온 함수가 ReLU 함수
![Image Description](https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAxNjEyMDFfMTM5%2FMDAxNDgwNTcyMTI1Mjk4.zDhI6hJxtCJtPLhuiCFfge25t0Lx0EKAhMVAphX7SwEg.swXsDNXszxlpYri94KA6j_XomJVit7XtQa9cszf2-DAg.PNG.koys007%2FScreen_Shot_2016-11-30_at_10_43_59_PM.png&type=sc960_832)