In [1]:
import numpy as np
from sklearn.datasets import make_blobs 

In [2]:
X, y = make_blobs(n_samples=200, n_features=2, centers=3, cluster_std=0.8, random_state=0)

In [4]:
X[:5]

array([[-1.69242695,  3.62202539],
       [ 0.69794036,  4.4288665 ],
       [ 1.10022802,  4.60631734],
       [-1.44872404,  3.38424521],
       [ 1.21486062,  5.36489604]])

In [5]:
y

array([2, 0, 0, 2, 0, 2, 1, 1, 0, 2, 0, 2, 0, 0, 0, 2, 1, 1, 0, 2, 2, 1,
       0, 0, 2, 0, 1, 2, 2, 2, 0, 0, 2, 0, 1, 1, 0, 1, 1, 2, 1, 2, 2, 2,
       0, 0, 0, 2, 0, 0, 0, 1, 2, 2, 2, 2, 1, 1, 0, 0, 2, 2, 0, 1, 1, 2,
       1, 1, 2, 1, 1, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 0, 0, 1, 1, 0, 0, 2,
       0, 1, 2, 2, 1, 0, 1, 0, 0, 2, 2, 1, 1, 0, 2, 0, 2, 0, 1, 0, 0, 1,
       0, 2, 1, 2, 0, 0, 0, 1, 2, 2, 1, 1, 2, 0, 1, 0, 2, 1, 2, 0, 2, 1,
       1, 1, 0, 1, 1, 0, 1, 2, 2, 2, 0, 1, 1, 0, 2, 2, 1, 0, 1, 2, 2, 2,
       0, 1, 1, 1, 0, 0, 2, 2, 2, 2, 0, 0, 1, 2, 1, 1, 0, 1, 0, 1, 2, 2,
       0, 2, 0, 1, 0, 2, 1, 1, 1, 0, 2, 1, 0, 0, 2, 2, 1, 1, 1, 1, 2, 1,
       0, 1])

In [ ]:
make_blobs

In [62]:
# n_samples가 array 형식이면 centers 를 'None' 이나 '개별 중심좌표' 로 설정해야됨
# n_samples의 array가 [a,b] 이면 centers가 2, [a,b,c] 이면 centers가 3
X, y = make_blobs(n_samples=[3, 3, 4], centers=([0,0],[1,1],[2,2]), n_features=2, random_state=0) 
print(X.shape)
print(y)

X,y = make_blobs(n_samples=10, centers=3, n_features=2, random_state=0)
print(X.shape)
print(y)

(10, 2)
[2 0 1 2 1 1 0 2 0 2]
(10, 2)
[0 0 1 0 2 2 2 1 1 0]


In [41]:
X

array([[2.81630525, 1.01933868],
       [2.49913075, 1.23133799],
       [1.9263585 , 4.15243012],
       [2.84382807, 3.32650945],
       [2.19931109, 2.35193717],
       [0.87305123, 4.71438583]])

In [33]:
import pandas as pd

clusterDF = pd.DataFrame(data = X, columns=['ftr1','ftr2'])

In [9]:
clusterDF

ftr1      ftr2
0  1.120314  5.758061
1  2.816305  1.019339
2 -1.213836  2.063787
3  0.873051  4.714386
4 -0.662468  2.175717
5  0.742851  1.463517
6 -4.079894  3.571501
7  3.549347  0.692505
8  2.499131  1.231338
9  1.926358  4.152430